baseURL: localhost
languageCode: es-es
title: PORTFOLIO
theme: personal-web
copyright: "© Sergio Hueso"


intro:
  main : "Hola!!, este es el currículum personal de Sergio Hueso Celma"
  sub : "Soy desarrolador web"

social:
  github : "https://github.com/sergiohc02/daw-sergiohc02"
  twitter : "https://twitter.com/sergiohc02"
  youtube : "https://www.youtube.com/channel/UC_7A1p11Kn5OOr9Xdv2Pjsw"
  instagram : "https://www.instagram.com/sergiohc02/"